# Create author that already died
POST http://localhost:3030/author HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1czJAdGVzdGUuY29tIiwiaWF0IjoxNjI3MjU2NDQ0LCJleHAiOjE2MjczNDI4NDQsInN1YiI6ImNjMzU2MzM0LWRlZDktNDQyMi05NDlmLTA2NTZlOTJhYTU4ZCJ9.G70GFA9XG9oKDaKTy8PWx97S7k1f5QLcpd7o_DbnUXU

{
    "name": "Friedrich Nietzsche",
    "bio": "German philosopher",
    "born_at": "1844-10-15",
    "died_at": "1900-08-25"
}

###

POST http://localhost:3030/author HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1czJAdGVzdGUuY29tIiwiaWF0IjoxNjI3MjU2NDQ0LCJleHAiOjE2MjczNDI4NDQsInN1YiI6ImNjMzU2MzM0LWRlZDktNDQyMi05NDlmLTA2NTZlOTJhYTU4ZCJ9.G70GFA9XG9oKDaKTy8PWx97S7k1f5QLcpd7o_DbnUXU

{
    "name": "Sigmund Freud",
    "bio": "German psychoanalyst",
    "born_at": "1856-05-06",
    "died_at": "1939-09-23"
}

###
# Create living author

POST http://localhost:3030/author HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1czJAdGVzdGUuY29tIiwiaWF0IjoxNjI3MjU2NDQ0LCJleHAiOjE2MjczNDI4NDQsInN1YiI6ImNjMzU2MzM0LWRlZDktNDQyMi05NDlmLTA2NTZlOTJhYTU4ZCJ9.G70GFA9XG9oKDaKTy8PWx97S7k1f5QLcpd7o_DbnUXU

{
    "name": "Slavoj Zizek",
    "bio": "Slovene Philosopher born in Yugoslavia",
    "born_at": "1949-03-21"
}

###
# create author without bio

POST http://localhost:3030/author HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1czJAdGVzdGUuY29tIiwiaWF0IjoxNjI3MjU2NDQ0LCJleHAiOjE2MjczNDI4NDQsInN1YiI6ImNjMzU2MzM0LWRlZDktNDQyMi05NDlmLTA2NTZlOTJhYTU4ZCJ9.G70GFA9XG9oKDaKTy8PWx97S7k1f5QLcpd7o_DbnUXU

{
    "name": "Sis",
    "born_at": "1111-11-11"
}

###
# Create aphorism with author name

POST http://localhost:3030/aphorisms HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1czJAdGVzdGUuY29tIiwiaWF0IjoxNjI3MjU2NDQ0LCJleHAiOjE2MjczNDI4NDQsInN1YiI6ImNjMzU2MzM0LWRlZDktNDQyMi05NDlmLTA2NTZlOTJhYTU4ZCJ9.G70GFA9XG9oKDaKTy8PWx97S7k1f5QLcpd7o_DbnUXU

{
    "text": "We live in a society",
    "like": 0,
    "author_name": "Sis"
}

###
# Get all authors

GET http://localhost:3030/authors HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1czJAdGVzdGUuY29tIiwiaWF0IjoxNjI3MjU2NDQ0LCJleHAiOjE2MjczNDI4NDQsInN1YiI6ImNjMzU2MzM0LWRlZDktNDQyMi05NDlmLTA2NTZlOTJhYTU4ZCJ9.G70GFA9XG9oKDaKTy8PWx97S7k1f5QLcpd7o_DbnUXU

###
# Get all aphorisms of author

GET http://localhost:3030/author/Sis/aphorism HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1czJAdGVzdGUuY29tIiwiaWF0IjoxNjI3MjU2NDQ0LCJleHAiOjE2MjczNDI4NDQsInN1YiI6ImNjMzU2MzM0LWRlZDktNDQyMi05NDlmLTA2NTZlOTJhYTU4ZCJ9.G70GFA9XG9oKDaKTy8PWx97S7k1f5QLcpd7o_DbnUXU

###
# Get author details

GET http://localhost:3030/author/Sis HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1czJAdGVzdGUuY29tIiwiaWF0IjoxNjI3MjU2NDQ0LCJleHAiOjE2MjczNDI4NDQsInN1YiI6ImNjMzU2MzM0LWRlZDktNDQyMi05NDlmLTA2NTZlOTJhYTU4ZCJ9.G70GFA9XG9oKDaKTy8PWx97S7k1f5QLcpd7o_DbnUXU