# sign-up
POST http://localhost:3030/users HTTP/1.1
Content-Type: application/json

{
    "username": "Mateus Galdino",
    "email": "mateus2@teste.com",
    "password": "12345",
    "age": 18,
    "dateOfBirth": "2002-11-29"
}

###

POST http://localhost:3030/users HTTP/1.1
Content-Type: application/json

{
    "username": "Tester tes",
    "email": "test@testing.com",
    "password": "12345",
    "age": 31,
    "dateOfBirth": "1990-5-13"
}

###
#sign-in

POST http://localhost:3030/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "mateus2@teste.com",
    "password": "12345"
}

### 
# Token testing

GET http://localhost:3030/api/auth/user HTTP/1.1
Authorization: Bearer ...

###
# Update description

PUT http://localhost:3030/api/users/description HTTP/1.1
Content-Type: application/json
Authorization: Bearer ...

{
    "description": "I am a programmer from Brasil"
}

###
# Get user by username
GET http://localhost:3030/user/mateus-Galdino HTTP/1.1
Content-Type: application/json
Authorization: Bearer ...

###
# Update user details

PUT http://localhost:3030/api/users/edit HTTP/1.1
Content-Type: application/json
Authorization: Bearer ...

{
    "name": "mateusg",
    "description": "I am a programmer from Brasil",
    "pronoun": "he/him"
}

###
# Get all entries with name

GET  http://localhost:3030/details/Friedrich-Nietzsche HTTP/1.1