# sign-up
POST http://localhost:3030/users HTTP/1.1
Content-Type: application/json

{
    "username": "Mateus Galdino",
    "email": "mateus2@teste.com",
    "password": "12345",
    "age": 18
}

###

POST http://localhost:3030/users HTTP/1.1
Content-Type: application/json

{
    "username": "Tester tes",
    "email": "test@testing.com",
    "password": "12345",
    "age": 31
}

###
#sign-in

POST http://localhost:3030/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "mateus2@teste.com",
    "password": "12345"
}

### 
# Token testing

GET http://localhost:3030/api/auth/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1czJAdGVzdGUuY29tIiwiaWF0IjoxNjI2MTgwOTU3LCJleHAiOjE2MjYyNjczNTcsInN1YiI6IjdkMzAyODA1LTg1NTctNDc1ZS1hYTljLTE3OGJkMGNiODQzYyJ9.tuK0dl2Xp_BIR0VeKTe442-WIcPry8rPCmb1Xhbg7aQ

###
# Update description

PUT http://localhost:3030/api/users/description HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGV1czJAdGVzdGUuY29tIiwiaWF0IjoxNjI2MTgwOTU3LCJleHAiOjE2MjYyNjczNTcsInN1YiI6IjdkMzAyODA1LTg1NTctNDc1ZS1hYTljLTE3OGJkMGNiODQzYyJ9.tuK0dl2Xp_BIR0VeKTe442-WIcPry8rPCmb1Xhbg7aQ

{
    "description": "I am a programmer from Brasil"
}